apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-v1-http
  namespace: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
      version: v1
      protocol: http
  template:
    metadata:
      labels:
        app: simple-app
        version: v1
        protocol: http
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: Exists
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: simple-app
              version: v1
              protocol: http
      containers:
        - name: http-app
          image: hashicorp/http-echo:latest
          args:
            - "-text=Simple App v1"
          ports:
            - containerPort: 5678
