apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-v4-http
  namespace: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
      version: v4
      protocol: http
  template:
    metadata:
      labels:
        app: simple-app
        version: v4
        protocol: http
    spec:
      containers:
        - name: http-app
          image: hashicorp/http-echo:latest
          args:
            - "-text=Simple App v4"
            - "-status-code=503"
          ports:
            - containerPort: 5678
